### ISSUE TITLE
我并不知道如何使用他？

### ISSUE THREAD

**Issue by IntThree** [AzurLaneTools/ljd#1]
使用
pip install ljd-0.1.7-py3-none-any.whl
我能安装他.
但如何使用他
我并不清楚
py ljd 报错
cd 到插件目录 
执行
py tools.py
报错
C:\Program Files\Python311\Lib\site-packages\ljd>py tools.py
Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\site-packages\ljd\tools.py", line 37, in <module>
    import ljd.ast.slotworks
  File "C:\Program Files\Python311\Lib\site-packages\ljd\ast\slotworks.py", line 13, in <module>
    from dataclasses import dataclass
  File "C:\Program Files\Python311\Lib\dataclasses.py", line 5, in <module>
    import inspect
  File "C:\Program Files\Python311\Lib\inspect.py", line 1024, in <module>
    class _ClassFinder(ast.NodeVisitor):
                       ^^^^^^^^^^^^^^^
AttributeError: module 'ast' has no attribute 'NodeVisitor

实在难以使用

**Comment by AutumnSun1996** [comment]
使用方式可以参考README中的[说明](https://github.com/AzurLaneTools/ljd#how-to-use)

这个repo的使用方式是作为第三方库, 没有提供命令行脚本

你需要将'Typical usage:'中的内容保存到新的文件, 如`main.py`, 修改输入/输出文件名, 再执行`python main.py`即可
